version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run lint
      - run: npm run test
